### ISSUE TITLE
[11.0] sale_discount_total produce the mismatch between actual discount and specified discount amount 

### ISSUE THREAD

**Issue by edison12347** [CybroOdoo/CybroAddons#84]
Trying the module on the demonstration data, showed the deviation of the calculated discount from the specified discount amount in Sale Order. Issue was found on Discount type = Amount.
Issue can be reproduced by creating order with GAP Analysis Service (Service product) from standard demonstration data for Odoo 11.0.
![discount_mismatch](https://user-images.githubusercontent.com/24977493/42633782-2b89f1c2-85ea-11e8-8b17-48410cea0f29.png)

**Comment by CybroOdoo** [comment]
Hello Edison,
Thanks for reaching out.
Its a known bug we cannot solve because python is not handling decimals above a limit. If you know the working of the module, in the case of a fixed amount discount. module computes the actual percentage and supplies to the order line so that discounts can be considered in tax computation.
here when we convert the fixed amount to a percentage, some decimal parts gets rounded and sometimes the discount amount becomes slightly higher or lower than the actual.
it will be grateful if you can look in to the issue and suggest a solution
